name: Fetch, Build and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 1 2 *' # every Feb 1st
  workflow_dispatch: # allow manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: pip install pandas openpyxl requests geopandas

      - name: Install Node.js dependencies
        run: npm ci

      - name: Fetch + sync data
        run: |
          npm run fetch:data
          npm run sync:data

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
